[general]
ipc_socket = false

[window]
decorations = "full"
startup_mode = "Maximized"

[window.dimensions]
columns = 80
lines = 24

[font]
size = 10.0

[font.normal]
family = "DejaVu Sans Mono"

[colors.primary]
foreground = "#b6bcc8"
background = "#282c34"

[colors.search.focused_match]
foreground = "#282c34"
background = "#97cb72"

[colors.search.matches]
foreground = "#97cb72"
background = "#282c34"

[colors.hints.start]
foreground = "#282c34"
background = "#97cb72"

[colors.hints.end]
foreground = "#97cb72"
background = "#282c34"

[colors.footer_bar]
foreground = "#282c34"
background = "#b6bcc8"

[colors.normal]
black   = "#282c34"
red     = "#e05c67"
green   = "#97cb72"
yellow  = "#f2c97d"
blue    = "#4aa4ed"
magenta = "#dd78c4"
cyan    = "#3fc7d9"
white   = "#b6bcc8"

[colors.bright]
black   = "#474e5c"
red     = "#e05c67"
green   = "#97cb72"
yellow  = "#f2c97d"
blue    = "#4aa4ed"
magenta = "#dd78c4"
cyan    = "#3fc7d9"
white   = "#e2e4e9"

[colors]
indexed_colors = [
    { index = 16, color = "#2c313a" },
    { index = 17, color = "#353b45" },
    { index = 18, color = "#7c879c" },
    { index = 19, color = "#99a2b2" },
    { index = 20, color = "#df8558" },
    { index = 21, color = "#b888e2" },
]

[bell]
color = "#b6bcc8"

[hints]
alphabet = "hutenosadimkc.r,z;"
